spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri:your mongo db uri address
      database: fitnessactivity

server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
