spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb+srv://mmiqbalmanawar:Manawar%407861%401234@forpractice.y4o7g.mongodb.net/fitnessactivity
      database: fitnessactivity

server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/