spring:
  application:
  name : aiservice
  data:
    mongodb:
      uri:
      database : fitnessrecommendation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
